services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27007:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERAME=${MONGO_INITDB_ROOT_USERAME}
      - MONGO_INITDB_ROOT_PASSWORD=$(MONGO_INITDB_ROOT_PASSWORD)
    restart: always

networks:
  backend:

volumes:
  mongodb_data: 